# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-18 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用户名称', max_length=100)),
                ('email', models.EmailField(help_text='用户邮箱', max_length=255)),
                ('url', models.URLField(blank=True, help_text='个人网站')),
                ('text', models.TextField(help_text='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='评论时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
